[package]
name = "wololopolo"
version = "0.1.0"
authors = ["Mice Pápai <qwhexz@gmail.com>"]

[dependencies]
rocket = {version = "0.3.14", features = ["tls"]}
rocket_codegen = "0.3.14"

[dependencies.rocket_contrib]
version = "0.3.14"
default-features = false
features = ["handlebars_templates"]